# Generated by Django 4.2.7 on 2025-04-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('STOCKS', 'Stocks'), ('INDICES', 'Indices'), ('COMMODITIES', 'Commodities'), ('FOREX', 'Forex')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
