# Generated by Django 4.2.7 on 2025-04-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=4)),
                ('lot', models.DecimalField(decimal_places=8, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tp', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('swap', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
