# Generated by Django 4.2.7 on 2025-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
