# Generated by Django 4.2.7 on 2025-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250505_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='api_key',
            new_name='account_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_provider',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('upi', 'UPI ID'), ('crypto', 'Cryptocurrency'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
