# Generated by Django 4.2.7 on 2025-05-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_withdrawal_payment_method_withdrawal_paypal_email_and_more'),
        ('myapp', 'fix_migration_issue'),
    ]

    operations = [
    ]
